# Generated by Django 3.1.2 on 2020-10-23 22:00

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[(todo.models.TaskPriority['HIGH'], 'high'), (todo.models.TaskPriority['MEDIUM'], 'medium'), (todo.models.TaskPriority['LOW'], 'low')], default=todo.models.TaskPriority['LOW'], max_length=20)),
                ('status', models.CharField(choices=[(todo.models.TaskStatus['PENDING'], 'pending'), (todo.models.TaskStatus['STARTED'], 'starting'), (todo.models.TaskStatus['COMPLETED'], 'completed'), (todo.models.TaskStatus['CANCELLED'], 'Cancelled')], default=todo.models.TaskStatus['PENDING'], max_length=40)),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(verbose_name='Last update')),
            ],
        ),
    ]
